Repository CMPUT301F24trojan1/trojan1-eventbuddy, pull requests merged in 2024-11, with the labels that each got.

#91 Updated most model classes and finished more DB queries
  .gitignore
  code/app/build.gradle.kts
  code/app/src/main/java/com/example/trojanplanner/controller/PhotoPicker.java
  code/app/src/main/java/com/example/trojanplanner/model/Admin.java
  code/app/src/main/java/com/example/trojanplanner/model/Database.java
  code/app/src/main/java/com/example/trojanplanner/model/Entrant.java
  code/app/src/main/java/com/example/trojanplanner/model/Event.java
  code/app/src/main/java/com/example/trojanplanner/model/Facility.java
  code/app/src/main/java/com/example/trojanplanner/model/Notification.java
  code/app/src/main/java/com/example/trojanplanner/model/Organizer.java
  code/app/src/test/java/com/example/trojanplanner/DatabaseTest.java
Labels: enhancement

#89 Made QR helper pop up slide show
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/InstructionSlideFragment.java
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/QRHelpFragment.java
  code/app/src/main/java/com/example/trojanplanner/controller/SlidePagerAdapter.java
  code/app/src/main/java/com/example/trojanplanner/view/QRActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/SlideShowActivity.java
  code/app/src/main/res/drawable/scanning_barcode.png
  code/app/src/main/res/drawable/text_background.xml
  code/app/src/main/res/layout/activity_qr.xml
  code/app/src/main/res/layout/activity_slide_show.xml
  code/app/src/main/res/layout/fragment_instruction_slide.xml
  code/app/src/main/res/layout/fragment_qr_helper.xml
Labels: enhancement

#137 changes to CI/CD pipeline, debugging directory structure
  .github/workflows/android.yml
Labels: bug

#140 Unit Tests run and build appropriately, making the same changes to UI…
  .github/workflows/android.yml
Labels: bug

#144 map implemented, with hardcoded points for now
  code/app/build.gradle.kts
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/trojanplanner/App.java
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/MarkedMapFragment.java
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/WaitlistFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/organizer/EventOptionsDialogFragment.java
  code/app/src/main/java/com/example/trojanplanner/java/MyFirebaseMessagingService.java
  code/app/src/main/java/com/example/trojanplanner/notifcations/MyFirebaseMessagingService.java
  code/app/src/main/java/com/example/trojanplanner/notifications/NotificationManager.java
  code/app/src/main/java/com/example/trojanplanner/view/QRActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/WelcomeActivity.java
  code/app/src/main/res/layout/fragment_marked_map.xml
  code/app/src/main/res/navigation/mobile_navigation.xml
  code/app/src/main/res/values/strings.xml
Labels: enhancement

#165 Latest building version
  code/app/src/main/java/com/example/trojanplanner/controller/BitmapGenerator.java
  code/app/src/main/java/com/example/trojanplanner/controller/EventArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminEventArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminFacilitiesArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminImagesArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminUsersArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/events/EventsFragment.java
  code/app/src/main/java/com/example/trojanplanner/model/Database.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminFacilitiesActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminImagesActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminUsersActivity.java
  code/app/src/main/res/drawable/profile_trump.png
  code/app/src/main/res/layout/activity_admin_events_list.xml
  code/app/src/main/res/layout/activity_admin_facilities_list.xml
  code/app/src/main/res/layout/activity_admin_users_list.xml
  code/app/src/main/res/layout/fragment_profile.xml
  code/app/src/main/res/layout/item_admin_event_card.xml
  code/app/src/main/res/layout/item_admin_facility_card.xml
  code/app/src/main/res/layout/item_image_card.xml
  code/app/src/main/res/layout/item_user_card.xml
  code/app/src/test/java/com/example/trojanplanner/PhotoPickerTest.java
Labels: enhancement

#173 activity_admin_qr.xml and AdminQRActivity -> Substitute for Profile, Multiple CRUCIAL changes including Leave Waitlist Button displaying properly, Enter Waitlist logic displaying button properly, Accept/Decline Invites, Lottery system logic, Notifs logic. UI changes based on Pending
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/NotificationSenderFragment.java
  code/app/src/main/java/com/example/trojanplanner/HelperFragments/WaitlistFragment.java
  code/app/src/main/java/com/example/trojanplanner/controller/EventArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/events/EventDetailsFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/entrant/EventDetailsDialogFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/organizer/EventOptionsDialogFragment.java
  code/app/src/main/java/com/example/trojanplanner/notifications/NotificationManager.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminQRActivity.java
  code/app/src/main/res/drawable/pending.png
  code/app/src/main/res/layout/activity_admin_qr.xml
  code/app/src/main/res/layout/fragment_event_details.xml
  code/app/src/main/res/layout/fragment_pending_list.xml
  code/app/src/main/res/layout/fragment_waitlist.xml
  code/app/src/main/res/layout/item_event_card.xml
  code/app/src/main/res/layout/item_waitlist.xml
  code/app/src/main/res/menu/admin_bottom_nav_menu.xml
  code/app/src/main/res/values/strings.xml
Labels: enhancement

#176 improper events will still populate QR might be helpful in understanding errors that might pop up
  code/app/src/androidTest/java/com/example/trojanplanner/ProfileFragmentTest.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminFacilitiesArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminImagesArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminQRArrayAdapter
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminQRArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminUsersArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/model/Database.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminFacilitiesActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminImagesActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminQRActivity.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminUsersActivity.java
  code/app/src/main/res/layout/activity_admin_events_list.xml
  code/app/src/main/res/layout/activity_admin_images_list.xml
  code/app/src/main/res/layout/activity_admin_qr.xml
  code/app/src/main/res/layout/item_admin_event_card.xml
  code/app/src/main/res/layout/item_qr_card.xml
Labels: enhancement

#178 Merging latest features to main
  code/app/src/main/java/com/example/trojanplanner/ProfileUtils/ProfileFragment.java
  code/app/src/main/java/com/example/trojanplanner/controller/BitmapGenerator.java
  code/app/src/main/java/com/example/trojanplanner/controller/EventArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/UserWaitlistAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/WaitlistAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminEventArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminFacilitiesArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminQRArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/controller/admin/AdminUsersArrayAdapter.java
  code/app/src/main/java/com/example/trojanplanner/events/EventDetailsFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/entrant/EventDetailsDialogFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/facility/FacilitySetupFragment.java
  code/app/src/main/java/com/example/trojanplanner/events/organizer/EventOptionsDialogFragment.java
  code/app/src/main/java/com/example/trojanplanner/model/Database.java
  code/app/src/main/java/com/example/trojanplanner/model/Event.java
  code/app/src/main/java/com/example/trojanplanner/model/Facility.java
  code/app/src/main/java/com/example/trojanplanner/model/User.java
  code/app/src/main/java/com/example/trojanplanner/view/admin/AdminImagesActivity.java
  code/app/src/main/res/layout/item_waitlist_popup.xml
Labels: bug, enhancement, Project Part 4
